version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_db
      MYSQL_USER: phdg
      MYSQL_PASSWORD: 123456
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
  spring-app:
    image: phdg/pjsocial:latest
    container_name: spring-container
    depends_on:
      - mysql
    ports:
      - 8080:8080
volumes:
  mysql-data:
